HttpServer:
  port: 80
  ip: 127.0.0.1
Routes: 'routes.yaml'
Logging:
  enabled: 1
  show_time: 1
  show_class: 1
  type: 3 #1 = console, 2 = file, 3 = both
  mode: 0 #0 = debug, 1 = info, 2 = notice, 3 = error
  log_file: 'console.log'
Session:
  file: 'data/session/'
  lifetime: PT30M #30min
  use_cookie: true
  key: 'session_id'