HttpServer:
  port: 80
  ip: 127.0.0.1
Routes: 'routes.yaml'
Logging:
  enabled: 1
  show_time: 1
  show_class: 1
  mode: 3 #1 = console, 2 = file, 3 = both
  log_file: 'console.log'
Session:
  file: 'data/session/'
  lifetime: PT30M #30min