HttpServer:
  port: 80
  ip: 127.0.0.1
Routes: 'routes.yaml'
Logging:
  enabled: 1
  show_time: 1
  show_class: 1
  type: 3 #1 = console, 2 = file, 3 = both
  mode: 3 #0 = debug, 1 = info, 2 = notice, 3 = error
  log_file: 'console.log'
Session:
  directory: 'data/session/'
  lifetime: PT30M #30min
  use_cookie: true
  key: 'session_id'
  keep_on_restart: false
Connection:
  test_connection:
    username: root
    password: ''
    host: 127.0.0.1
    port: 3306
    charset: utf8mb4
    dbname: test_connection
    main: true
Managers:
  Manager\UserManager:
    connection: test_connection
    table: users
    entity: Entity\User
    primary_key: id