Handler\TestHandler:
  route: /test
  methods: [GET]
  middleware:
    - ReactWeb\Session\Middleware

Handler\LoginHandler:
  route: /login
  methods: [GET]

Handler\HTMLHandler:
  route: /html
  methods: [GET]

Handler\FormHandler:
  route: /form
  methods: [GET, POST]
